dates:
    #  start: 2020-09-24T00
    #  end: 2020-09-28T18
  start: 2019-09-24T00
  end: 2019-09-28T18
  freq: 6h

fhrs: [0, 6]

members:
  start: 0
  end: 1

store_path: /global/cfs/cdirs/m4718/timothys/gefs/one-degree/forecasts.zarr
chunks:
  t0: 1
  fhr: 1
  member: 1
  pressure: 1
  latitude: -1
  longitude: -1
