dates:
  start: 2017-01-01T00
  end: 2017-01-08T18
  freq: 6h

fhrs: [0, 6]

members:
  start: 0
  end: 3

store_path: ./quick.zarr
chunks:
  t0: 1
  fhr: 1
  member: 1
  pressure: 1
  latitude: -1
  longitude: -1
