dates:
  start: 2020-02-17T00
  end: 2020-02-17T12
  freq: 6h

fhrs: [0, 6]

members:
  start: 0
  end: 1

store_path: ./sample-gefs.zarr
chunks:
  t0: 1
  fhr: 1
  member: 1
  pressure: 1
  latitude: -1
  longitude: -1
