FV3Dataset:
    file_prefixes:
        - bfg_
        - sfg_

    path_out        : "example-replay-1deg"
    forecast_hours  : [0, 6]

    chunks_in:
        time        : 1
        pfull       : 1
        grid_yt     : -1
        grid_xt     : -1

    chunks_out:
        time        : 1
        pfull       : 127
        grid_yt     : 60
        grid_xt     : 60

    coords:
        - phalf
        - pfull
        - grid_xt
        - grid_yt
        - ak
        - bk

    data_vars:
        - tmp
        - ugrd
        - vgrd
        - dpres
        - delz
        - spfh
        - o3mr
        - soilt1
        - soilt2
        - soilt3
        - soilt4
        - soill1
        - soill2
        - soill3
        - soill4
        - soilw1
        - soilw2
        - soilw3
        - soilw4
        - snod
        - prateb_ave
        - pressfc
        - weasd
        - f10m
        - sfcr
        - land

MOM6Dataset:
    file_prefixes:
        - ocn_
    path_out        : "example-replay-1deg"
    forecast_hours  : [0]
    chunks_in:
        time        : 1
        z_l         : 1
        z_i         : 1
        yh          : -1
        xh          : -1
        yq          : -1
        xq          : -1

    chunks_out:
        time        : 1
        z_l         : -1
        z_i         : -1
        lat         : 60
        lon         : 60

    coords:
        - xh
        - xq
        - yh
        - yq
        - z_l
        - geolon_c
        - geolat_c
        - geolon_u
        - geolat_u
        - geolon_v
        - geolat_v
        - wet_c
        - wet_u
        - wet_v
        - sin_rot
        - cos_rot

    data_vars:
        - uo
        - vo
        - temp
        - so
        - SSH
        - MLD_0125

    regrid:
        rotation_file:
        weights_file_t2t:
        weights_file_u2t:
        weights_file_v2t:
        periodic: True

CICE6Dataset:
    file_prefixes:
        - "iceh_ic."
    path_out        : "example-replay-1deg"
    forecast_hours  : [0]
    chunks_in:
        nc          : 1
        nkice       : 1
        nkaer       : 1
        nksnow      : 1
        nj          : -1
        ni          : -1

    chunks_out:
        time        : 1
        NCAT        : 5
        VGRDi       : 7
        VGRDa       : 5
        VGRDs       : 5
        nj          : 30
        ni          : 30

    coords:
        - TLON
        - TLAT
        - ULON
        - ULAT
        - NCAT
        - tmask
        - blkmask
        - tarea
        - uarea
        - ANGLE
        - ANGLET
        - VGRDa
        - VGRDi
        - VGRDs

    data_vars:
        - Tinz
        - aicen
        - vicen
        - uvel
        - vvel
        - hi
        - Tsfc
        - aice
