FV3Dataset:
    file_prefixes:
        - bfg_
        - sfg_

    path_out       : "gcs://noaa-ufs-gefsv13replay/ufs-hr1/1.00-degree/03h-freq/zarr/"
    coords_path_out: "gcs://noaa-ufs-gefsv13replay/ufs-hr1/1.00-degree/coordinates/zarr/"
    forecast_hours  : [0, 3]

    chunks_in:
        # estimated 37MB per chunk (the full 3D field)
        time        : 1
        pfull       : 127
        grid_yt     : 192
        grid_xt     : 384

    chunks_out:
        time        : 1
        pfull       : 127
        grid_yt     : 192
        grid_xt     : 384

    coords:
        - phalf
        - pfull
        - grid_xt
        - grid_yt
        - ak
        - bk

    data_vars:
        - acond
        - albdo_ave
        - alnsf
        - alnwf
        - alvsf
        - alvwf
        - c0
        - cd
        - cduvb_ave
        - cldfra
        - cnvprcp
        - cnwat
        - cpofp
        - cprat_ave
        - cpratb_ave
        - crain
        - csdlf
        - csdsf
        - csulf
        - csulftoa
        - csusf
        - csusftoa
        - cwork_aveclm
        - dconv
        - dlwrf
        - dlwrf_ave
        - dswrf
        - dswrf_ave
        - dswrf_avetoa
        - dtcool
        - duvb_ave
        - ecan_acc
        - edir_acc
        - etran_acc
        - evbs_ave
        - evcw_ave
        - f10m
        - facsf
        - facwf
        - ffhh
        - ffmm
        - fldcp
        - fricv
        - frozr
        - frozrb
        - frzr
        - frzrb
        - gflux
        - gflux_ave
        - hgt_hyblev1
        - hpbl
        - icec
        - icetk
        - land
        - lfrac
        - lhtfl
        - lhtfl_ave
        - nbdsf_ave
        - nddsf_ave
        - orog
        - pah_ave
        - pahi
        - pevpr
        - pevpr_ave
        - prate_ave
        - prateb_ave
        - pres_avehcb
        - pres_avehct
        - pres_avelcb
        - pres_avelct
        - pres_avemcb
        - pres_avemct
        - prescnvclb
        - prescnvclt
        - pressfc
        - pwat
        - qrain
        - rhonewsn
        - sbsno_ave
        - sfcr
        - sfexc
        - shdmax
        - shdmin
        - shtfl
        - shtfl_ave
        - sltyp
        - snoalb
        - snod
        - snohf
        - snowc_ave
        - soill1
        - soill2
        - soill3
        - soill4
        - soilm
        - soilt1
        - soilt2
        - soilt3
        - soilt4
        - soilw1
        - soilw2
        - soilw3
        - soilw4
        - sotyp
        - spfh2m
        - spfh_hyblev1
        - spfhmax_max2m
        - spfhmin_min2m
        - ssrun_acc
        - sunsd_acc
        - tcdc_avebndcl
        - tcdc_aveclm
        - tcdc_avehcl
        - tcdc_avelcl
        - tcdc_avemcl
        - tcdccnvcl
        - tg3
        - tisfc
        - tmax_max2m
        - tmin_min2m
        - tmp2m
        - tmp_avehct
        - tmp_avelct
        - tmp_avemct
        - tmp_hyblev1
        - tmpsfc
        - tprcp
        - trans_ave
        - tref
        - tsnowp
        - tsnowpb
        - u-gwd_ave
        - uflx_ave
        - ugrd10m
        - ugrd_hyblev1
        - ulwrf
        - ulwrf_ave
        - ulwrf_avetoa
        - uswrf
        - uswrf_ave
        - uswrf_avetoa
        - v-gwd_ave
        - vbdsf_ave
        - vddsf_ave
        - veg
        - vflx_ave
        - vgrd10m
        - vgrd_hyblev1
        - vtype
        - w0
        - wa_acc
        - watr_acc
        - wd
        - weasd
        - wilt
        - xs
        - xt
        - xtts
        - xu
        - xv
        - xz
        - xzts
        - zc
        - clwmr
        - delz
        - dpres
        - dzdt
        - grle
        - hgtsfc
        - icmr
        - nicp
        - ntrnc
        - o3mr
        - rwmr
        - snmr
        - spfh
        - tmp
        - ugrd
        - vgrd

MOM6Dataset:
    file_prefixes:
        - ocn_
    path_out        : "example-replay-1deg"
    forecast_hours  : [0]
    chunks_in:
        time        : 1
        z_l         : 1
        z_i         : 1
        yh          : -1
        xh          : -1
        yq          : -1
        xq          : -1

    chunks_out:
        time        : 1
        z_l         : -1
        z_i         : -1
        lat         : 60
        lon         : 60

    coords:
        - xh
        - xq
        - yh
        - yq
        - z_l
        - geolon_c
        - geolat_c
        - geolon_u
        - geolat_u
        - geolon_v
        - geolat_v
        - wet_c
        - wet_u
        - wet_v
        - sin_rot
        - cos_rot

    data_vars:
        - uo
        - vo
        - temp
        - so
        - SSH
        - MLD_0125

    regrid:
        rotation_file: mom6_grid_1.00_degree.nc
        weights_file_t2t:
        weights_file_u2t:
        weights_file_v2t:
        periodic: True