# This uses actios:
#  checkout: https://github.com/actions/checkout
#  cache: https://github.com/actions/cache
#  codecov-action: https://github.com/codecov/codecov-action

name: CI
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
    logLevel:
      options:
        - info
        - warning
        - debug


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build (${{ matrix.python-version }} | ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Create conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          cache-downloads: true
          cache-environment: true
          micromamba-version: "latest"
          environment-file: environment.yaml
          create-args: python=${{ matrix.python-version }}
          init-shell: bash
      - name: Install ufs2arco
        shell: bash -l {0}
        run: |
          python -V
          python -c "import setuptools; print(setuptools.__version__)"
          python -m pip install -e . --no-deps
      - name: Run Unit Tests
        shell: bash -l {0}
        run: |
          python -V
          coverage run --rcfile=coverage.toml -m pytest --verbose
      - name: Get coverage report
        shell: bash -l {0}
        run: |
          coverage report -m ; coverage xml

  windows-build:
    name: Build (${{ matrix.python-version }} | ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"]
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Create conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          cache-downloads: true
          cache-environment: true
          micromamba-version: "latest"
          environment-file: environment.yaml
          create-args: python=${{ matrix.python-version }}
          init-shell: powershell
      - name: Install ufs2arco
        shell: pwsh
        run: |
          python -V
          python -c "import setuptools; print(setuptools.__version__)"
          python -m pip install -e . --no-deps
      - name: Run Unit Tests
        shell: pwsh
        run: |
          python -V
          coverage run --rcfile=coverage.toml -m pytest --verbose
      - name: Get coverage report
        shell: pwsh
        run: |
          coverage report -m ; coverage xml
