name: Manual Integration Tests

on:
  workflow_dispatch:
    logLevel:
      options:
        - info
        - warning
        - debug

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build (${{ matrix.python-version }} | ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Create conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          cache-downloads: true
          cache-environment: true
          micromamba-version: "latest"
          environment-file: environment.yaml
          create-args: python=${{ matrix.python-version }}
          init-shell: bash
      - name: Install ufs2arco
        shell: bash -l {0}
        run: |
          python -V
          python -c "import setuptools; print(setuptools.__version__)"
          python -m pip install -e . --no-deps
      - name: Run Integration Tests
        shell: bash -l {0}
        run: |
          python -V
    			coverage run --rcfile=coverage.toml -m pytest tests/integration --verbose
      - name: Get coverage report
        shell: bash -l {0}
        run: |
          coverage report -m ; coverage xml
