name: Manual PR Tests

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  post_comment:
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Post Comment with Manual Trigger Instructions
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const targetRepo = github.event.pull_request.head.repo.full_name;  // Forked repo
            const targetOwner = targetRepo.split('/')[0];  // Owner of the forked repo
            const targetRepoName = targetRepo.split('/')[1];  // Repo name of the forked repo

            // Post the comment in the feature branch's repository
            github.rest.issues.createComment({
              owner: targetOwner,
              repo: targetRepoName,
              issue_number: context.payload.pull_request.number,
              body: "🔍 This PR has a **manual test workflow**! To trigger it:\n\n"
                    + "1. Go to the [Actions tab](https://github.com/${{ github.repository }}/actions).\n"
                    + "2. Select **Manual PR Tests**.\n"
                    + "3. Click **Run workflow** and choose your branch.\n\n"
                    + "⚡ This workflow only runs when manually triggered!"
            });
